// Naruto-inspired roster (private fan build). Stats are multipliers around 1.0.
// jutsu.* names index into JUTSU in jutsu.js; awaken describes the low-HP transformation.
export const CHARACTERS = [
  {
    id: 'naruto',
    name: 'NARUTO',
    title: 'Uzumaki Naruto — Jinchūriki Cửu Vĩ',
    element: 'wind',
    kanji: '九',
    colors: {
      jacket: 0xf07a12,
      accent: 0x1b1e2a,
      pants: 0xe8700f,
      skin: 0xf1c29a,
      hair: 0xffd23a,
      scarf: 0xf07a12,
      eye: 0x3aa8ff,
      chakra: 0x4fd8ff,
    },
    hair: 'spiky',
    marks: 'whiskers',
    scarf: false,
    build: 1.0,
    stats: { hp: 1.0, speed: 1.08, power: 1.0 },
    jutsu: { special: 'rasengan', special2: 'kageBunshin', ultimate: 'rasenshuriken' },
    special: { name: 'Rasengan', desc: 'Cầu xoáy chakra lao tới nghiền nát đối thủ' },
    special2: { name: 'Uzumaki Liên Đạn', desc: 'Hai phân thân đá tung đối thủ, bản thể giáng gót xuống' },
    ultimate: { name: 'Phong Độn: Rasenshuriken', desc: 'Phi tiêu gió khổng lồ bám theo, nghiền rồi nổ tung' },
    awaken: { name: 'Cửu Vĩ Chakra', kind: 'kyuubi', color: 0xff6a10, eye: 0xff2a10 },
  },
  {
    id: 'sasuke',
    name: 'SASUKE',
    title: 'Uchiha Sasuke — Kẻ Báo Thù',
    element: 'lightning',
    kanji: '雷',
    colors: {
      jacket: 0xe9e6ee,
      accent: 0x4a2c7a,
      pants: 0x23202c,
      skin: 0xf0d0b4,
      hair: 0x161a26,
      scarf: 0x5a3a96,
      eye: 0xff2020,
      chakra: 0xb88cff,
    },
    hair: 'swept',
    scarf: false,
    rope: 0x6b3fb4,
    build: 0.96,
    stats: { hp: 0.95, speed: 1.14, power: 1.0 },
    jutsu: { special: 'chidori', special2: 'housenka', ultimate: 'kirin' },
    special: { name: 'Chidori', desc: 'Ngàn chim sấm trên tay, lướt xuyên qua đối thủ' },
    special2: { name: 'Hỏa Độn: Phượng Tiên Hỏa', desc: 'Năm cầu lửa nhỏ tỏa ra rồi bám theo mục tiêu' },
    ultimate: { name: 'Kirin', desc: 'Gọi bão sét giáng xuống đầu đối thủ' },
    awaken: { name: 'Mangekyō · Susanoo', kind: 'susanoo', color: 0x9a5cff, eye: 0xff1010 },
  },
  {
    id: 'itachi',
    name: 'ITACHI',
    title: 'Uchiha Itachi — Akatsuki',
    element: 'fire',
    kanji: '月',
    colors: {
      jacket: 0x14141a,
      accent: 0xc8202a,
      pants: 0x1a1a22,
      skin: 0xeccbb0,
      hair: 0x101016,
      scarf: 0xb3211f,
      eye: 0xff1010,
      chakra: 0xff3a3a,
    },
    hair: 'ponytail',
    cloak: { color: 0x101014, cloud: 0xd0202a },
    scarf: false,
    build: 0.98,
    stats: { hp: 0.95, speed: 1.04, power: 1.08 },
    jutsu: { special: 'goukakyuu', special2: 'amaterasu', ultimate: 'tsukuyomi' },
    special: { name: 'Hỏa Độn: Hào Hỏa Cầu', desc: 'Phun quả cầu lửa khổng lồ' },
    special2: { name: 'Amaterasu', desc: 'Hắc viêm bùng cháy ngay trên người đối thủ' },
    ultimate: { name: 'Tsukuyomi', desc: 'Kéo đối thủ vào thế giới ảo thuật đỏ máu' },
    awaken: { name: 'Susanoo', kind: 'susanoo', color: 0xff4a3a, eye: 0xff1010 },
  },
  {
    id: 'gaara',
    name: 'GAARA',
    title: 'Sabaku no Gaara — Kazekage',
    element: 'sand',
    kanji: '愛',
    colors: {
      jacket: 0x7a2a26,
      accent: 0xcfb07a,
      pants: 0x5a2420,
      skin: 0xf0d2b6,
      hair: 0xb8231a,
      scarf: 0xcfb07a,
      eye: 0x4ad6a8,
      chakra: 0xffc26a,
    },
    hair: 'short',
    marks: 'ai',
    gourd: true,
    headband: false,
    scarf: false,
    build: 0.97,
    stats: { hp: 1.12, speed: 0.92, power: 1.08 },
    jutsu: { special: 'sandSpears', special2: 'sandCoffin', ultimate: 'sandTsunami' },
    special: { name: 'Sa Thương Liên Hoàn', desc: 'Giáo cát trồi lên thành hàng tiến về đối thủ' },
    special2: { name: 'Sa Phược Cữu', desc: 'Cát bao bọc đối thủ rồi siết nát' },
    ultimate: { name: 'Lưu Sa Bạo Lưu', desc: 'Sóng thần cát cuốn phăng cả chiến trường' },
    awaken: { name: 'Nhất Vĩ Shukaku', kind: 'shukaku', color: 0xffc26a, eye: 0xffe070 },
  },
  {
    id: 'madara',
    name: 'MADARA',
    title: 'Uchiha Madara — Bóng Ma Uchiha',
    element: 'fire',
    kanji: '斑',
    colors: {
      jacket: 0x8a1e22,
      accent: 0x3a2a24,
      pants: 0x1c1a1f,
      skin: 0xe6c2a4,
      hair: 0x0e0e14,
      scarf: 0x8a1e22,
      eye: 0xb48cff,
      chakra: 0x7a8cff,
    },
    hair: 'wild',
    scarf: false,
    armor: true,
    headband: false,
    build: 1.06,
    stats: { hp: 1.08, speed: 0.98, power: 1.12 },
    jutsu: { special: 'gokaMekkyaku', special2: 'fireDragon', ultimate: 'tengaiShinsei' },
    special: { name: 'Hỏa Độn: Hào Hỏa Diệt Khước', desc: 'Biển lửa khổng lồ quét qua phía trước' },
    special2: { name: 'Hỏa Độn: Long Viêm Phóng Ca', desc: 'Rồng lửa uốn lượn truy đuổi đối thủ' },
    ultimate: { name: 'Thiên Ngại Chấn Tinh', desc: 'Kéo thiên thạch từ trời cao giáng xuống' },
    awaken: { name: 'Rinnegan · Susanoo', kind: 'susanoo', color: 0x4a6cff, eye: 0xc8a8ff },
  },
  {
    id: 'lee',
    name: 'ROCK LEE',
    title: 'Rock Lee — Mãnh Thú Xanh',
    element: 'taijutsu',
    kanji: '剛',
    colors: {
      jacket: 0x2f8a3a,
      accent: 0xf07a12,
      pants: 0x2f8a3a,
      skin: 0xf1c8a4,
      hair: 0x0b0b10,
      scarf: 0xc8202a,
      eye: 0x111111,
      chakra: 0x6aff7a,
    },
    hair: 'bowl',
    marks: 'brows',
    legWarmers: 0xf07a12,
    headband: false,
    scarf: false,
    build: 1.0,
    stats: { hp: 0.95, speed: 1.2, power: 1.05 },
    jutsu: { special: 'leafHurricane', special2: 'primaryLotus', ultimate: 'morningPeacock' },
    special: { name: 'Mộc Diệp Toàn Phong', desc: 'Lao tới xoay người đá liên hoàn như lốc xoáy' },
    special2: { name: 'Biểu Liên Hoa', desc: 'Đá tung đối thủ lên trời, quấn lấy rồi cắm đầu xuống đất' },
    ultimate: { name: 'Bát Môn: Triêu Khổng Tước', desc: 'Mở cửa thứ sáu, trăm quyền lửa nở như đuôi công' },
    awaken: { name: 'Bát Môn Độn Giáp', kind: 'gates', color: 0x6aff7a, eye: 0xffffff },
  },
];

export const byId = (id) => CHARACTERS.find((c) => c.id === id);
