// Original ninja roster. Stats are multipliers around 1.0.
export const CHARACTERS = [
  {
    id: 'kaito',
    name: 'KAITO',
    title: 'Phong Ảnh — Ninja Gió',
    element: 'wind',
    kanji: '風',
    colors: {
      jacket: 0x1f2f55,
      accent: 0x2ec4b6,
      pants: 0x23252b,
      skin: 0xe8b996,
      hair: 0xd9dde3,
      scarf: 0x26b8a8,
      eye: 0x6ff7ff,
      chakra: 0x5ff2ff,
    },
    hair: 'spiky',
    build: 1.0,
    stats: { hp: 1.0, speed: 1.08, power: 1.0 },
    special: { name: 'Phong Cầu Xoáy', desc: 'Quả cầu gió lao tới nghiền nát đối thủ' },
    ultimate: { name: 'Thiên Phong Đại Tuyền', desc: 'Quả cầu bão khổng lồ phóng ra như phi tiêu' },
  },
  {
    id: 'ren',
    name: 'REN',
    title: 'Hỏa Long — Ninja Lửa',
    element: 'fire',
    kanji: '火',
    colors: {
      jacket: 0x171314,
      accent: 0xc32a2a,
      pants: 0x1c1a1d,
      skin: 0xdcae8c,
      hair: 0x5a1312,
      scarf: 0xb3211f,
      eye: 0xff5a1f,
      chakra: 0xff6a1a,
    },
    hair: 'swept',
    build: 1.04,
    stats: { hp: 1.0, speed: 1.0, power: 1.08 },
    special: { name: 'Hỏa Cầu Thuật', desc: 'Phun quả cầu lửa khổng lồ' },
    ultimate: { name: 'Hỏa Long Diệt Thế', desc: 'Rồng lửa truy đuổi và thiêu rụi đối thủ' },
  },
  {
    id: 'yume',
    name: 'YUME',
    title: 'Lôi Điểu — Ninja Sấm',
    element: 'lightning',
    kanji: '雷',
    colors: {
      jacket: 0xe6e3ea,
      accent: 0x6a35a6,
      pants: 0x2a2236,
      skin: 0xf0c6a8,
      hair: 0x14121a,
      scarf: 0x7b3fc4,
      eye: 0xc69bff,
      chakra: 0xb88cff,
    },
    hair: 'ponytail',
    build: 0.93,
    stats: { hp: 0.92, speed: 1.16, power: 0.98 },
    special: { name: 'Lôi Nha Đột', desc: 'Lưỡi sét xuyên thấu, lao đi như chớp' },
    ultimate: { name: 'Thiên Lôi Phán Xét', desc: 'Gọi bão sét giáng xuống đầu đối thủ' },
  },
  {
    id: 'tetsu',
    name: 'TETSU',
    title: 'Thạch Quyền — Ninja Đất',
    element: 'earth',
    kanji: '土',
    colors: {
      jacket: 0x4a4a32,
      accent: 0xb38a3d,
      pants: 0x2e2a22,
      skin: 0xc8946c,
      hair: 0x1e1a16,
      scarf: 0x8a6a2a,
      eye: 0xffc457,
      chakra: 0xffb347,
    },
    hair: 'short',
    build: 1.16,
    stats: { hp: 1.15, speed: 0.88, power: 1.15 },
    special: { name: 'Địa Thứ Liên Hoàn', desc: 'Gai đá trồi lên thành hàng tiến về đối thủ' },
    ultimate: { name: 'Sơn Băng Địa Liệt', desc: 'Thiên thạch đá khổng lồ rơi xuống từ trời' },
  },
];

export const byId = (id) => CHARACTERS.find((c) => c.id === id);
